### ISSUE TITLE
Sorry to bother

### ISSUE THREAD

**Issue by RaptaG** [tarampampam/tarampampam#8]
Um hey there!

I'm trying to register a website in https://github.com/tarampampam/free-domains but I get this:

![image](https://github.com/tarampampam/tarampampam/assets/77157639/8ee0c1e1-966c-4926-a8b7-9cc01b5d2aa5)
Happens to both issues and PRs..
If there are any updates just let me know @tarampampam

**Comment by tarampampam** [comment]
@RaptaG Try now, please
